# .streamlit/secrets.toml

jwt_secret = "dfgjlohdnodhjtrtwewedsdfdsvbcbbncnhhjreertsdfkghdgjlkhdgjkhdjkgdfhgk"
db_url = "sqlite:///equity_app.db"

# opzionale: crea admin automaticamente al primo avvio
initial_admin_pw = "passwordforte"